import os
import argparse

parser = argparse.ArgumentParser(description="TSER-KD")

parser.add_argument('--run_name', type=str, help='Experiment name.')
parser.add_argument('--dataset', default='cifar10', type=str, help='Dataset used to train the model.\nPossible candidates are [cifar10, mnist].')
parser.add_argument('--auto_aug', default=True, type=bool, help='Applies AutoAugmentation on the dataset.\nValid only on cifar10.')
parser.add_argument('--cutout', default=True, type=bool, help='Applies CutOut on the dataset.\nValid only on cifar10.')
parser.add_argument('--batch_size', default=32, type=int, help='Batch size for the dataset.')
parser.add_argument('--num_workers', default=2, type=int, help='Number of threads used by the data loaders.')
# parser.add_argument('--experiment_type', default='kd', type=str, help='Type of training to perform.\nPossible experiments are: [ann, snn, kd].')
parser.add_argument('--t_weight', default=None, type=str, help='State dict path for the teacher model.')
parser.add_argument('--teacher_arch', default='resnet-34', type=str, help='Teacher model architecture.\nPossible models are: [resnet-34, resnet-19, resnet-18].')
parser.add_argument('--transfer', default=False, type=bool, help='Flag that handles the transfer learning for ResNet19.')
parser.add_argument('--transfer_weight', default=None, type=str, help='State dict path for ResNet18 transfer learning for ResNet19.')
parser.add_argument('--trainable_weights', default=True, type=bool, help='Flag that handles the trainable weights that are transferred.')
parser.add_argument('--optimizer', default='adamw', type=str, help='Optimizer for training the model.\nPossible optimizers are: [adamw, sgd].')
parser.add_argument('--lr', default=3e-3, type=float, help='Learning rate.')
parser.add_argument('--wd', default=5e-4, type=float, help='Weight decay for optimizer.')
# parser.add_argument('--momentum', default=0.9, type=float, help='Momentum for optimizer.')
parser.add_argument('--scheduler', default='cosine', type=str, help='Learning rate scheduler for training.\nPossible schedulers are: [cosine, reduce].')
# parser.add_argument('--lr_patience', default=0, type=int, help='LR patience for ReduceLROnPlateau scheduler.')
# parser.add_argument('--lr_factor', default=0.6, type=float, help='LR factor for ReduceLROnPlateau scheduler.')
parser.add_argument('--epochs', default=300, type=int, help='Training epochs.')
# parser.add_argument('--alpha', default=1e-2, type=float, help='KL and CE weighting parameter in KD.')
# parser.add_argument('--gamma', default=1e-3, type=float, help='ER weighting parameter in KD.')
# parser.add_argument('--tau', default=5, type=float, help='Temperature.')
parser.add_argument('--model_path', default='data/teacher_models/best_acc.pth', type=str, help='Path to save the best model weights.')

args = parser.parse_args()
args_dict = vars(args)
